name: CI/CD with Codecov

on:
  push:
    branches:
      - main
      - develop
      - '*'
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore CodeCoverage/CodeCoverage.sln

      # Step 4: Build the application
      - name: Build application
        working-directory: CodeCoverage
        run: dotnet build CodeCoverage.sln --no-restore

      # Step 5: Run tests with coverage
      - name: Test with coverage
        run: dotnet test ./NUnitTestProject.csproj --collect:"XPlat Code Coverage;Format=cobertura"

      # Step 6: Upload coverage to Codecov
      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: MobassherRashedi/TestCoverage_2
          files: "**/TestResults/*/coverage.cobertura.xml"
          fail_ci_if_error: true
          verbose: true
